### ISSUE TITLE
configureGit does not checkout latest version from tags

### ISSUE THREAD

**Issue by landonreed** [conveyal/maven-semantic-release#13] opened 2019-01-07 15:40 UTC
Using this with https://github.com/conveyal/datatools-server currently throws a bad snapshot version error. Releases for the repository were done on a different repository (catalogueglobal) so I had to push those tagged releases to the conveyal repo.

I expected the release to work after this step, but for some reason maven-semantic-release recognizes the latest tagged version as `3.1.0` even though it's actually `3.2.0`. I'm not sure if this is due to weirdness with the tags after pushing them or what, but perhaps there could be an issue with how maven-semantic-release sorts these tags. I did notice that when I used `git tag | sort -V | tail -1` I was left with `3.2.0`, but I'm not sure if that would be a reliable way to grab the latest version going forward

**Comment by evansiroky** [comment] 2019-01-07 16:19
semantic-release is working as intended.  The 3.2.0 tag has not been merged into the conveyal repo yet.

<img width="672" alt="screen shot 2019-01-07 at 8 16 35 am" src="https://user-images.githubusercontent.com/3112493/50779342-e9c40000-1254-11e9-9828-61b522bc9789.png">

**Closed by evansiroky** 2019-01-07 16:19 UTC
Labels: bug

**Comment by landonreed** [comment] 2019-01-07 18:06
Yea, I think my confusion here was that I was expecting it to draw the previously released version number from the git tags and not the master branch.
